name: Build container
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DOCKER_REPO_PREFIX: inspircd
      DOCKER_REPO_NAME: inspircd-docker
      INSP_VERSION: v3.10.0
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: Prepare environment
        run: |
          sudo apt-get -qq update
          sudo apt-get -y -o Dpkg::Options::="--force-confnew" install moby-engine moby-cli
          sudo apt-get install -y openssl parallel
      -
        name: Docker meta
        if: github.repository == 'inspircd/inspircd-docker' && github.ref == 'refs/heads/master'
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REPO_PREFIX }}/${{ env.DOCKER_REPO_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ env.INSP_VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.INSP_VERSION }}
            type=semver,pattern={{major}},value=${{ env.INSP_VERSION }}
      - 
        name: Set up QEMU
        if: github.repository == 'inspircd/inspircd-docker' && github.ref == 'refs/heads/master'
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        if: github.repository == 'inspircd/inspircd-docker' && github.ref == 'refs/heads/master'
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.repository == 'inspircd/inspircd-docker' && github.ref == 'refs/heads/master'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        if: github.repository == 'inspircd/inspircd-docker' && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: VERSION=${{ env.INSP_VERSION }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: 
      - 
        name: Docker Hub Description
        if: github.repository == 'inspircd/inspircd-docker' && github.ref == 'refs/heads/master'
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPO_PREFIX }}/${{ env.DOCKER_REPO_NAME }}
          short-description: Official image for InspIRCd Internet Relay Chat server. https://www.inspircd.org
          readme-filepath: README.md
